name: Deploy Dev

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-website:
    name: Deploy Website to dev.2dtiler-website.pages.dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v6.0.2

      - name: Install and build site
        uses: withastro/action@v6.1.0
        with:
          node-version: 24
          package-manager: bun@1.3.11
          build-cmd: bun run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: bun
          wranglerVersion: 4.81.0
          command: pages deploy dist --project-name=2dtiler-website --branch=dev
